import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${inter.className} bg-black`}>

  {/* <QueryClientProvider client={queryClient}> */}
  {/* <ToastContainer
    position="top-center"
    autoClose={2000}
    hideProgressBar={false}
    newestOnTop={false}
    closeOnClick
    rtl={false}
    pauseOnFocusLoss
    draggable
    pauseOnHover
    theme="dark" /> */}

  <main className='h-screen flex flex-col gap-[1px] bg-black text-white'>
   
    {/* <PageLoader show={isLoading}/> */}
   
      {children}
  </main>

  {/* </QueryClientProvider> */}
</body>
    </html>
  );
}
